services:
  skulk:
    build: ./skulk
    ports:
      - "50052:50052"
      - "11632:11632"
    volumes:
      - skulk-data:/app/db
    networks:
      skulk-net:
        ipv4_address: "172.26.0.4"
    environment:
      - RUST_LOG=debug
      - HOST_IP_ADDR=172.26.0.4
  predatorfox_1:
    build: ./fox/predatorfox
    healthcheck:
      test: ["CMD-SHELL", "/grpc_health_probe-linux-amd64 -addr=$$HOST_IP_ADDR:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - db-data-1:/app/data
      - pq-data-1:/app/data/parquets
    ports:
      - "50051:50051"
      - "50635:11635"
    networks:
      skulk-net:
        ipv4_address: "172.26.0.2"
    environment:
      - HOST_IP_ADDR=172.26.0.2
      - RUST_LOG=info
      - model_cache:/root/.cache/huggingface/
  collectorfox_1:
    build: ./fox/collectorfox
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://$$HOST_IP_ADDR:11635/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - db-data-1:/app/data
      - pq-data-1:/app/data/parquets
    network_mode: "service:predatorfox_1"
    environment:
      - HOST_IP_ADDR=172.26.0.2
      - SKULK_IP_ADDR=172.26.0.4
      - PARQUET_PATH=/app/data/parquets
  predatorfox_2:
    build: ./fox/predatorfox
    healthcheck:
      test: ["CMD-SHELL", "/grpc_health_probe-linux-amd64 -addr=$$HOST_IP_ADDR:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - db-data-2:/app/data
      - pq-data-2:/app/data/parquets
    ports:
      - "51051:50051"
      - "51635:11635"
    networks:
      skulk-net:
        ipv4_address: "172.26.0.3"
    environment:
      - HOST_IP_ADDR=172.26.0.3
      - RUST_LOG=info
      - model_cache:/root/.cache/huggingface/
  collectorfox_2:
    build: ./fox/collectorfox
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://$$HOST_IP_ADDR:11635/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - db-data-2:/app/data
      - pq-data-2:/app/data/parquets
    network_mode: "service:predatorfox_2"
    environment:
      - HOST_IP_ADDR=172.26.0.3
      - SKULK_IP_ADDR=172.26.0.4
      - PARQUET_PATH=/app/data/parquets
  test_client_script:
    build: ./tests
    environment:
      - SKULK_URL=172.26.0.4
      - COLLECTOR_URL_1=172.26.0.3
      - COLLECTOR_URL_2=172.26.0.2
    depends_on:
      skulk:
        condition: service_started
      collectorfox_1:
        condition: service_healthy
      collectorfox_2:
        condition: service_healthy
      predatorfox_1:
        condition: service_healthy
      predatorfox_2:
        condition: service_healthy
    networks:
      - skulk-net
  test_client_node:
    build: ./tests
    command:
    - /bin/sh
    - -c
    - "tail -f /dev/null"
    networks:
      - skulk-net
    depends_on:
      skulk:
        condition: service_started
      collectorfox_1:
        condition: service_healthy
      collectorfox_2:
        condition: service_healthy
      predatorfox_1:
        condition: service_healthy
      predatorfox_2:
        condition: service_healthy
volumes:
  db-data-1:
  db-data-2:
  pq-data-1:
  pq-data-2:
  skulk-data:
  model_cache:


networks:
  skulk-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
          gateway: "172.26.0.1"
