# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cmd.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cmd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcmd.proto\x12\x0fpredatorfox.cmd\"e\n\x07\x43ommand\x12.\n\x08\x63md_type\x18\x01 \x02(\x0e\x32\x1c.predatorfox.cmd.CommandType\x12*\n\x05query\x18\x02 \x02(\x0b\x32\x1b.predatorfox.cmd.SkulkQuery\"\x85\x01\n\nSkulkQuery\x12\x0f\n\x07\x64\x61taset\x18\x01 \x02(\t\x12\x0f\n\x07\x63olumns\x18\x02 \x03(\t\x12\x12\n\npredicates\x18\x03 \x01(\t\x12\x32\n\x0cvector_query\x18\x04 \x01(\x0b\x32\x1c.predatorfox.cmd.VectorQuery\x12\r\n\x05limit\x18\x05 \x01(\x05\"C\n\x0bVectorQuery\x12\x0e\n\x06\x63olumn\x18\x01 \x02(\t\x12\x15\n\rtarget_vector\x18\x02 \x03(\x02\x12\r\n\x05top_k\x18\x03 \x02(\x05*%\n\x0b\x43ommandType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05QUERY\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cmd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDTYPE']._serialized_start=338
  _globals['_COMMANDTYPE']._serialized_end=375
  _globals['_COMMAND']._serialized_start=30
  _globals['_COMMAND']._serialized_end=131
  _globals['_SKULKQUERY']._serialized_start=134
  _globals['_SKULKQUERY']._serialized_end=267
  _globals['_VECTORQUERY']._serialized_start=269
  _globals['_VECTORQUERY']._serialized_end=336
# @@protoc_insertion_point(module_scope)
